baseURL:
languageCode: en-us
title: A Naked Hugo Site Title
disableKinds:
  - taxonomy
  - taxonomyTerm
enableRobotsTXT: true
paginate: 1
params:
  description: >-
    Description
  twitter_user: kris_ray
  twitter_link: https://twitter.com/
  facebook_link: http://www.facebook.com/
  instagram_link: https://www.instagram.com/
  #google_analytics: UA-
  paid_for: Paid for by Language Goes Here
  form_endpoint: 123456
